export const UI_MESSAGES = {
  ERRORS: {
    GENERIC: 'An unexpected error occurred. Please try again.',
    LOGIN_FAILED: 'Login failed. Please try again.',
    REGISTRATION_FAILED: 'Registration failed. Please try again.',
    PROFILE_LOAD_FAILED: 'Failed to load profile',
    PROFILE_UPDATE_FAILED: 'Failed to update profile',
    USERNAME_UPDATE_FAILED: 'Failed to update username',
    PHOTO_UPDATE_FAILED: 'Failed to update profile photo',
    PHOTO_REMOVE_FAILED: 'Failed to remove profile photo',
    VERIFICATION_FAILED: 'Failed to send verification email',
    RESET_EMAIL_FAILED: 'Failed to send reset email',
    PASSWORD_RESET_FAILED: 'Failed to reset password',
    DEACTIVATION_FAILED: 'Failed to deactivate account',
    PASSWORDS_DONT_MATCH: 'Passwords do not match',
    INVALID_RESET_TOKEN: 'Invalid reset token',
    INVALID_URL: 'Please enter a valid URL',
    INVALID_PHOTO_URL: 'Please enter a valid photo URL',
    USERNAME_LENGTH: 'Username must be between 3 and 20 characters',
  },
  SUCCESS: {
    EMAIL_SENT: 'Email sent!',
    VERIFICATION_SENT: 'Verification email sent! Check your inbox.',
    USERNAME_UPDATED: 'Username updated successfully',
    PHOTO_UPDATED: 'Profile photo updated successfully',
    PHOTO_REMOVED: 'Profile photo removed',
    PASSWORD_RESET: 'Password reset successfully',
    EMAIL_VERIFIED: 'Email Verified!',
  },
  LOADING: {
    SIGNING_IN: 'Signing in...',
    CREATING_ACCOUNT: 'Creating account...',
    SENDING: 'Sending...',
    PROCESSING: 'Processing...',
    SAVING: 'Saving...',
    REMOVING: 'Removing...',
    RESETTING: 'Resetting...',
    LOADING: 'Loading...',
    LOADING_PROFILE: 'Loading profile...',
    COMPLETING_SIGNIN: 'Completing sign in...',
    VERIFYING: 'Verifying your email...',
  },
  TITLES: {
    WELCOME_BACK: 'Welcome back',
    SIGN_UP_FREE: 'Sign up for free',
    RESET_PASSWORD: 'Reset your password',
    CHOOSE_NEW_PASSWORD: 'Choose new password',
    EMAIL_VERIFICATION: 'Email Verification',
    RESEND_VERIFICATION: 'Resend Verification',
    PROFILE_SETTINGS: 'Profile Settings',
    INVALID_LINK: 'Invalid Link',
    VERIFICATION_FAILED: 'Verification Failed',
    DEACTIVATE_ACCOUNT: 'Deactivate Account?',
  },
  BUTTONS: {
    SIGN_IN: 'Sign in',
    SIGN_UP: 'Sign up',
    SEND_RESET_LINK: 'Send reset link',
    RESET_PASSWORD: 'Reset password',
    RESEND_VERIFICATION: 'Resend verification email',
    CONTINUE_GOOGLE: 'Continue with Google',
    VERIFY_NOW: 'Verify now',
    CHANGE_PHOTO: 'Change photo',
    REMOVE: 'Remove',
    EDIT: 'Edit',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    LOG_OUT: 'Log out',
    DEACTIVATE: 'Deactivate',
    GO_HOME: 'Go to Home',
    BACK_TO_LOGIN: 'Back to login',
    REQUEST_NEW_LINK: 'Request new verification link',
  },
  PLACEHOLDERS: {
    EMAIL: 'Email address',
    EMAIL_OR_USERNAME: 'Email or username',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    PASSWORD_MIN_6: 'Password (at least 6 characters)',
    NEW_PASSWORD: 'New password',
    CONFIRM_PASSWORD: 'Confirm password',
    IMAGE_URL: 'Enter image URL (e.g., https://example.com/photo.jpg)',
  },
  DESCRIPTIONS: {
    SIGN_IN_SUBTITLE: 'Sign in to continue to Music App',
    SIGN_UP_SUBTITLE: 'Create your account to get started',
    RESET_SUBTITLE: 'Enter your email to receive a reset link',
    NEW_PASSWORD_SUBTITLE: 'Make it strong and memorable',
    RESEND_SUBTITLE: 'Enter your email to receive a new verification link',
    USERNAME_HINT: 'Username must be between 3 and 20 characters',
    PHOTO_HINT: 'Enter a direct link to an image (must be publicly accessible)',
    USERNAME_DISPLAY: 'This is how others will see you',
  },
  NOTIFICATIONS: {
    EMAIL_VERIFIED_24H: 'Check your inbox for a verification link. It will expire in 24 hours.',
    PASSWORD_RESET_1H: 'Check your inbox for a password reset link. It will expire in 1 hour.',
    DEACTIVATION_WARNING: 'Your account will be scheduled for permanent deactivation in 7 days. You can cancel this by logging in within that period.',
    EMAIL_VERIFIED_SUCCESS: 'Your email has been successfully verified. Redirecting to login...',
    INVALID_RESET_LINK: 'This password reset link is invalid or has expired.',
    VERIFY_EMAIL_PROMPT: 'Please check your inbox and verify your email address to access all features.',
  },
};

export const QUERY_KEYS = {
  PROFILE: 'profile',
  CURRENT_USER: 'currentUser',
};

export const ROUTE_PARAMS = {
  TOKEN: 'token',
  ERROR: 'error',
  SUCCESS: 'success',
  VERIFICATION: 'verification',
  VERIFICATION_PENDING: 'pending',
};